USE [medman]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Address##AddressPK]    Script Date: 08/01/2021 2:30:19 AM ******/
CREATE NONCLUSTERED INDEX [Address##AddressPK] ON [dbo].[Address]
(
	[EntitySID] ASC,
	[Class] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Address##Class]    Script Date: 08/01/2021 2:30:19 AM ******/
CREATE NONCLUSTERED INDEX [Address##Class] ON [dbo].[Address]
(
	[Class] ASC
)
INCLUDE([EntitySID],[Line1],[Line2],[City],[State],[Zip]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Address##Class#State]    Script Date: 08/01/2021 2:30:19 AM ******/
CREATE NONCLUSTERED INDEX [Address##Class#State] ON [dbo].[Address]
(
	[Class] ASC,
	[State] ASC
)
INCLUDE([EntitySID],[Line1],[City],[Zip]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Address##Entity##Class]    Script Date: 08/01/2021 2:30:19 AM ******/
CREATE NONCLUSTERED INDEX [Address##Entity##Class] ON [dbo].[Address]
(
	[EntitySID] ASC,
	[Class] ASC,
	[prrowid] ASC
)
INCLUDE([State]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Address##ZipCode]    Script Date: 08/01/2021 2:30:19 AM ******/
CREATE NONCLUSTERED INDEX [Address##ZipCode] ON [dbo].[Address]
(
	[Zip] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PK__Address__CE87783469E64737]    Script Date: 08/01/2021 2:30:19 AM ******/
ALTER TABLE [dbo].[Address] ADD PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO


