USE [medman]
GO

/****** Object:  Index [Claim##Account]    Script Date: 08/01/2021 2:33:57 AM ******/
CREATE NONCLUSTERED INDEX [Claim##Account] ON [dbo].[Claim]
(
	[AccountSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

/****** Object:  Index [Claim##Ailment]    Script Date: 08/01/2021 2:33:57 AM ******/
CREATE NONCLUSTERED INDEX [Claim##Ailment] ON [dbo].[Claim]
(
	[AilmentSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Claim##ClaimNumber]    Script Date: 08/01/2021 2:33:57 AM ******/
CREATE NONCLUSTERED INDEX [Claim##ClaimNumber] ON [dbo].[Claim]
(
	[ClaimNumber] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

/****** Object:  Index [Claim##ClaimPK]    Script Date: 08/01/2021 2:33:57 AM ******/
CREATE NONCLUSTERED INDEX [Claim##ClaimPK] ON [dbo].[Claim]
(
	[ClaimSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

/****** Object:  Index [Claim##ParentClaims]    Script Date: 08/01/2021 2:33:57 AM ******/
CREATE NONCLUSTERED INDEX [Claim##ParentClaims] ON [dbo].[Claim]
(
	[ParentClaimSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Claim##PracLegacyClaim]    Script Date: 08/01/2021 2:33:57 AM ******/
CREATE NONCLUSTERED INDEX [Claim##PracLegacyClaim] ON [dbo].[Claim]
(
	[PracticeID] ASC,
	[LegacyClaimNumber] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

/****** Object:  Index [Claim##PracPatientClaim]    Script Date: 08/01/2021 2:33:58 AM ******/
CREATE NONCLUSTERED INDEX [Claim##PracPatientClaim] ON [dbo].[Claim]
(
	[PracticeID] ASC,
	[PatientID] ASC,
	[ClaimSID] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Claim##PracticeClaimNumber]    Script Date: 08/01/2021 2:33:58 AM ******/
CREATE NONCLUSTERED INDEX [Claim##PracticeClaimNumber] ON [dbo].[Claim]
(
	[PracticeID] ASC,
	[ClaimNumber] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PK__Claim__CE877834F3F59683]    Script Date: 08/01/2021 2:33:58 AM ******/
ALTER TABLE [dbo].[Claim] ADD PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO


