USE [medman]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [CountryState##CountryState]    Script Date: 08/01/2021 2:35:58 AM ******/
CREATE NONCLUSTERED INDEX [CountryState##CountryState] ON [dbo].[CountryState]
(
	[CountryCode] ASC,
	[State] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [CountryState##CountryStatePK]    Script Date: 08/01/2021 2:35:58 AM ******/
CREATE NONCLUSTERED INDEX [CountryState##CountryStatePK] ON [dbo].[CountryState]
(
	[CountryCode] ASC,
	[StateCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [CountryState##StateCode]    Script Date: 08/01/2021 2:35:58 AM ******/
CREATE NONCLUSTERED INDEX [CountryState##StateCode] ON [dbo].[CountryState]
(
	[StateCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PK__CountryS__CE877834388EA6AB]    Script Date: 08/01/2021 2:35:58 AM ******/
ALTER TABLE [dbo].[CountryState] ADD PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO


