USE [medman]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Entity##Class]    Script Date: 08/01/2021 2:37:54 AM ******/
CREATE NONCLUSTERED INDEX [Entity##Class] ON [dbo].[Entity]
(
	[Class] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Entity##Class#EntitySID]    Script Date: 08/01/2021 2:37:54 AM ******/
CREATE NONCLUSTERED INDEX [Entity##Class#EntitySID] ON [dbo].[Entity]
(
	[Class] ASC
)
INCLUDE([EntitySID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

/****** Object:  Index [Entity##EntityPK]    Script Date: 08/01/2021 2:37:54 AM ******/
CREATE NONCLUSTERED INDEX [Entity##EntityPK] ON [dbo].[Entity]
(
	[EntitySID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Entity##GlobalID]    Script Date: 08/01/2021 2:37:54 AM ******/
CREATE NONCLUSTERED INDEX [Entity##GlobalID] ON [dbo].[Entity]
(
	[GlobalID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Entity##SortName]    Script Date: 08/01/2021 2:37:54 AM ******/
CREATE NONCLUSTERED INDEX [Entity##SortName] ON [dbo].[Entity]
(
	[SortName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PK__Entity__CE877834E12CC90B]    Script Date: 08/01/2021 2:37:54 AM ******/
ALTER TABLE [dbo].[Entity] ADD PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO


