USE [medman]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [LookupType##Class]    Script Date: 08/01/2021 2:40:01 AM ******/
CREATE NONCLUSTERED INDEX [LookupType##Class] ON [dbo].[LookupType]
(
	[Class] ASC,
	[LookupType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [LookupType##Description]    Script Date: 08/01/2021 2:40:01 AM ******/
CREATE NONCLUSTERED INDEX [LookupType##Description] ON [dbo].[LookupType]
(
	[Description] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [LookupType##DescriptionWord]    Script Date: 08/01/2021 2:40:01 AM ******/
CREATE NONCLUSTERED INDEX [LookupType##DescriptionWord] ON [dbo].[LookupType]
(
	[Description] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [LookupType##LookupTypePK]    Script Date: 08/01/2021 2:40:01 AM ******/
CREATE NONCLUSTERED INDEX [LookupType##LookupTypePK] ON [dbo].[LookupType]
(
	[LookupType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PK__LookupTy__CE87783460EFEF7C]    Script Date: 08/01/2021 2:40:01 AM ******/
ALTER TABLE [dbo].[LookupType] ADD PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO


