USE [medman]
GO

/****** Object:  Index [Person##ContactID]    Script Date: 08/01/2021 2:44:03 AM ******/
CREATE NONCLUSTERED INDEX [Person##ContactID] ON [dbo].[Person]
(
	[HeadOfHouseholdID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Person##CreateStamp]    Script Date: 08/01/2021 2:44:03 AM ******/
CREATE NONCLUSTERED INDEX [Person##CreateStamp] ON [dbo].[Person]
(
	[CreateStamp] ASC
)
INCLUDE([PersonID],[CreateUser]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Person##CreateStamp#LastName]    Script Date: 08/01/2021 2:44:03 AM ******/
CREATE NONCLUSTERED INDEX [Person##CreateStamp#LastName] ON [dbo].[Person]
(
	[CreateStamp] ASC
)
INCLUDE([PersonID],[LastName]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Person##CreateStamp#PersonID]    Script Date: 08/01/2021 2:44:03 AM ******/
CREATE NONCLUSTERED INDEX [Person##CreateStamp#PersonID] ON [dbo].[Person]
(
	[CreateStamp] ASC
)
INCLUDE([PersonID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

/****** Object:  Index [Person##DOB]    Script Date: 08/01/2021 2:44:03 AM ******/
CREATE NONCLUSTERED INDEX [Person##DOB] ON [dbo].[Person]
(
	[DOB] ASC,
	[PersonID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Person##MobilePhone]    Script Date: 08/01/2021 2:44:03 AM ******/
CREATE NONCLUSTERED INDEX [Person##MobilePhone] ON [dbo].[Person]
(
	[DNMobilePhone] ASC,
	[PersonID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Person##Name]    Script Date: 08/01/2021 2:44:03 AM ******/
CREATE NONCLUSTERED INDEX [Person##Name] ON [dbo].[Person]
(
	[LastName] ASC,
	[FirstName] ASC,
	[MiddleName] ASC,
	[PersonID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Person##NumberName]    Script Date: 08/01/2021 2:44:03 AM ******/
CREATE NONCLUSTERED INDEX [Person##NumberName] ON [dbo].[Person]
(
	[PersonNumber] ASC,
	[FirstName] ASC,
	[LastName] ASC,
	[MiddleName] ASC,
	[DOB] ASC
)
INCLUDE([PersonID],[SortName],[SSN],[Sex],[Email],[Language]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

/****** Object:  Index [Person##ParentGuardianID]    Script Date: 08/01/2021 2:44:03 AM ******/
CREATE NONCLUSTERED INDEX [Person##ParentGuardianID] ON [dbo].[Person]
(
	[ParentGuardianID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Person##PersonNumber]    Script Date: 08/01/2021 2:44:03 AM ******/
CREATE NONCLUSTERED INDEX [Person##PersonNumber] ON [dbo].[Person]
(
	[PersonNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

/****** Object:  Index [Person##PersonPK]    Script Date: 08/01/2021 2:44:03 AM ******/
CREATE NONCLUSTERED INDEX [Person##PersonPK] ON [dbo].[Person]
(
	[PersonID] ASC
)
INCLUDE([PersonNumber],[SortName],[DOB]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Person##Phone]    Script Date: 08/01/2021 2:44:03 AM ******/
CREATE NONCLUSTERED INDEX [Person##Phone] ON [dbo].[Person]
(
	[HomePhone] ASC,
	[PersonID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Person##SortName]    Script Date: 08/01/2021 2:44:03 AM ******/
CREATE NONCLUSTERED INDEX [Person##SortName] ON [dbo].[Person]
(
	[SortName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Person##SortPersonNumber]    Script Date: 08/01/2021 2:44:03 AM ******/
CREATE NONCLUSTERED INDEX [Person##SortPersonNumber] ON [dbo].[Person]
(
	[DNSortPersonNumber] ASC,
	[PersonID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Person##Soundex]    Script Date: 08/01/2021 2:44:03 AM ******/
CREATE NONCLUSTERED INDEX [Person##Soundex] ON [dbo].[Person]
(
	[SoundEx] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Person##SSN]    Script Date: 08/01/2021 2:44:03 AM ******/
CREATE NONCLUSTERED INDEX [Person##SSN] ON [dbo].[Person]
(
	[SSN] ASC,
	[PersonID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PK__Person__CE877834DD889985]    Script Date: 08/01/2021 2:44:03 AM ******/
ALTER TABLE [dbo].[Person] ADD PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO


