USE [medman]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Phone##Class]    Script Date: 08/01/2021 2:44:37 AM ******/
CREATE NONCLUSTERED INDEX [Phone##Class] ON [dbo].[Phone]
(
	[Class] ASC
)
INCLUDE([prrowid],[EntitySID],[Number]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Phone##ClassEntityNumber]    Script Date: 08/01/2021 2:44:37 AM ******/
CREATE NONCLUSTERED INDEX [Phone##ClassEntityNumber] ON [dbo].[Phone]
(
	[Class] ASC
)
INCLUDE([EntitySID],[Number]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Phone##EntityClassNumber]    Script Date: 08/01/2021 2:44:37 AM ******/
CREATE NONCLUSTERED INDEX [Phone##EntityClassNumber] ON [dbo].[Phone]
(
	[EntitySID] ASC,
	[Class] ASC,
	[Number] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Phone##Number]    Script Date: 08/01/2021 2:44:37 AM ******/
CREATE NONCLUSTERED INDEX [Phone##Number] ON [dbo].[Phone]
(
	[Number] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Phone##PhonePK]    Script Date: 08/01/2021 2:44:37 AM ******/
CREATE NONCLUSTERED INDEX [Phone##PhonePK] ON [dbo].[Phone]
(
	[EntitySID] ASC,
	[Class] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PK__Phone__CE87783494AB99A6]    Script Date: 08/01/2021 2:44:37 AM ******/
ALTER TABLE [dbo].[Phone] ADD PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO


