USE [medman]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PK__PlanClai__CE8778342618341B]    Script Date: 08/01/2021 2:46:43 AM ******/
ALTER TABLE [dbo].[PlanClaimData] ADD PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

/****** Object:  Index [PlanClaimData##ClaimSID]    Script Date: 08/01/2021 2:46:44 AM ******/
CREATE NONCLUSTERED INDEX [PlanClaimData##ClaimSID] ON [dbo].[PlanClaimData]
(
	[ClaimSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PlanClaimData##PlanClaimDataPK]    Script Date: 08/01/2021 2:46:44 AM ******/
CREATE NONCLUSTERED INDEX [PlanClaimData##PlanClaimDataPK] ON [dbo].[PlanClaimData]
(
	[PlanID] ASC,
	[PolicyNumber] ASC,
	[ClaimSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO


