USE [medman]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PK__PlanAltI__CE877834FF372A2A]    Script Date: 08/01/2021 11:55:11 PM ******/
ALTER TABLE [dbo].[PlanAltID] ADD PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PlanAltID##AidTag#ID]    Script Date: 08/01/2021 11:55:11 PM ******/
CREATE NONCLUSTERED INDEX [PlanAltID##AidTag#ID] ON [dbo].[PlanAltID]
(
	[AidTag] ASC,
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PlanAltID##ClassTagID]    Script Date: 08/01/2021 11:55:11 PM ******/
CREATE NONCLUSTERED INDEX [PlanAltID##ClassTagID] ON [dbo].[PlanAltID]
(
	[AidClass] ASC,
	[AidTag] ASC,
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PlanAltID##PlanAltIDPK]    Script Date: 08/01/2021 11:55:11 PM ******/
CREATE NONCLUSTERED INDEX [PlanAltID##PlanAltIDPK] ON [dbo].[PlanAltID]
(
	[PlanID] ASC,
	[AidClass] ASC,
	[AidTag] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PlanAltID##ProviderTag]    Script Date: 08/01/2021 11:55:11 PM ******/
CREATE NONCLUSTERED INDEX [PlanAltID##ProviderTag] ON [dbo].[PlanAltID]
(
	[AidClass] ASC,
	[ProviderTag] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO


