USE [medman]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PK__PlanAltN__CE8778341AD14DB4]    Script Date: 08/01/2021 11:55:46 PM ******/
ALTER TABLE [dbo].[PlanAltName] ADD PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PlanAltName##AltNameWord]    Script Date: 08/01/2021 11:55:46 PM ******/
CREATE NONCLUSTERED INDEX [PlanAltName##AltNameWord] ON [dbo].[PlanAltName]
(
	[AltName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

/****** Object:  Index [PlanAltName##PlanAltNamePK]    Script Date: 08/01/2021 11:55:46 PM ******/
CREATE NONCLUSTERED INDEX [PlanAltName##PlanAltNamePK] ON [dbo].[PlanAltName]
(
	[PlanID] ASC,
	[SequenceNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PlanAltName##PlanName]    Script Date: 08/01/2021 11:55:46 PM ******/
CREATE NONCLUSTERED INDEX [PlanAltName##PlanName] ON [dbo].[PlanAltName]
(
	[PlanID] ASC,
	[AltName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO


