USE [medman]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PK__Policy__CE8778346D2F22F5]    Script Date: 08/01/2021 2:47:32 AM ******/
ALTER TABLE [dbo].[Policy] ADD PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Policy##Description]    Script Date: 08/01/2021 2:47:32 AM ******/
CREATE NONCLUSTERED INDEX [Policy##Description] ON [dbo].[Policy]
(
	[Description] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Policy##PolicyNumber]    Script Date: 08/01/2021 2:47:32 AM ******/
CREATE NONCLUSTERED INDEX [Policy##PolicyNumber] ON [dbo].[Policy]
(
	[PolicyNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Policy##PolicyPK]    Script Date: 08/01/2021 2:47:32 AM ******/
CREATE NONCLUSTERED INDEX [Policy##PolicyPK] ON [dbo].[Policy]
(
	[PlanID] ASC,
	[PolicyNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

/****** Object:  Index [Policy##Subscriber]    Script Date: 08/01/2021 2:47:32 AM ******/
CREATE NONCLUSTERED INDEX [Policy##Subscriber] ON [dbo].[Policy]
(
	[SubscriberID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO


