USE [medman]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PK__Practice__CE877834272C8114]    Script Date: 08/01/2021 2:48:47 AM ******/
ALTER TABLE [dbo].[Practice] ADD PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

/****** Object:  Index [Practice##CBOPractice]    Script Date: 08/01/2021 2:48:47 AM ******/
CREATE NONCLUSTERED INDEX [Practice##CBOPractice] ON [dbo].[Practice]
(
	[CBOPractice] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Practice##Name]    Script Date: 08/01/2021 2:48:47 AM ******/
CREATE NONCLUSTERED INDEX [Practice##Name] ON [dbo].[Practice]
(
	[SortName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Practice##PracticeCode]    Script Date: 08/01/2021 2:48:47 AM ******/
CREATE NONCLUSTERED INDEX [Practice##PracticeCode] ON [dbo].[Practice]
(
	[PracticeCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

/****** Object:  Index [Practice##PracticePK]    Script Date: 08/01/2021 2:48:47 AM ******/
CREATE NONCLUSTERED INDEX [Practice##PracticePK] ON [dbo].[Practice]
(
	[PracticeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Practice##SharePerson]    Script Date: 08/01/2021 2:48:47 AM ******/
CREATE NONCLUSTERED INDEX [Practice##SharePerson] ON [dbo].[Practice]
(
	[SharePerson] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO


