USE [medman]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PK__Practice__CE8778347B96B9CD]    Script Date: 08/01/2021 2:49:19 AM ******/
ALTER TABLE [dbo].[PracticePlan] ADD PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PracticePlan##BatchCode]    Script Date: 08/01/2021 2:49:19 AM ******/
CREATE NONCLUSTERED INDEX [PracticePlan##BatchCode] ON [dbo].[PracticePlan]
(
	[BatchCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PracticePlan##EMCFormCode]    Script Date: 08/01/2021 2:49:19 AM ******/
CREATE NONCLUSTERED INDEX [PracticePlan##EMCFormCode] ON [dbo].[PracticePlan]
(
	[EMCFormCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PracticePlan##FixedProcChargeGLTag]    Script Date: 08/01/2021 2:49:19 AM ******/
CREATE NONCLUSTERED INDEX [PracticePlan##FixedProcChargeGLTag] ON [dbo].[PracticePlan]
(
	[FixedProcChargeGLTag] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

/****** Object:  Index [PracticePlan##OTAFProfileSID]    Script Date: 08/01/2021 2:49:19 AM ******/
CREATE NONCLUSTERED INDEX [PracticePlan##OTAFProfileSID] ON [dbo].[PracticePlan]
(
	[OTAFProfileSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PracticePlan##PaperFormCode]    Script Date: 08/01/2021 2:49:19 AM ******/
CREATE NONCLUSTERED INDEX [PracticePlan##PaperFormCode] ON [dbo].[PracticePlan]
(
	[PaperFormCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

/****** Object:  Index [PracticePlan##PracticePlanPK]    Script Date: 08/01/2021 2:49:19 AM ******/
CREATE NONCLUSTERED INDEX [PracticePlan##PracticePlanPK] ON [dbo].[PracticePlan]
(
	[PracticeID] ASC,
	[PlanID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PracticePlan##WithholdingGLTag]    Script Date: 08/01/2021 2:49:19 AM ******/
CREATE NONCLUSTERED INDEX [PracticePlan##WithholdingGLTag] ON [dbo].[PracticePlan]
(
	[WithholdingGLTag] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PracticePlan##WriteDownGLTag]    Script Date: 08/01/2021 2:49:19 AM ******/
CREATE NONCLUSTERED INDEX [PracticePlan##WriteDownGLTag] ON [dbo].[PracticePlan]
(
	[WriteDownGLTag] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PracticePlan##WriteOffGLTag]    Script Date: 08/01/2021 2:49:19 AM ******/
CREATE NONCLUSTERED INDEX [PracticePlan##WriteOffGLTag] ON [dbo].[PracticePlan]
(
	[WriteOffGLTag] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO


