USE [medman]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PK__Procedur__CE877834FCF7CD7B]    Script Date: 08/01/2021 2:50:03 AM ******/
ALTER TABLE [dbo].[Procedure] ADD PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Procedure##Class]    Script Date: 08/01/2021 2:50:03 AM ******/
CREATE NONCLUSTERED INDEX [Procedure##Class] ON [dbo].[Procedure]
(
	[Class] ASC,
	[ProcedureCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Procedure##DepartmentCode]    Script Date: 08/01/2021 2:50:03 AM ******/
CREATE NONCLUSTERED INDEX [Procedure##DepartmentCode] ON [dbo].[Procedure]
(
	[DepartmentCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Procedure##Description]    Script Date: 08/01/2021 2:50:03 AM ******/
CREATE NONCLUSTERED INDEX [Procedure##Description] ON [dbo].[Procedure]
(
	[Description] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Procedure##DescriptionWord]    Script Date: 08/01/2021 2:50:03 AM ******/
CREATE NONCLUSTERED INDEX [Procedure##DescriptionWord] ON [dbo].[Procedure]
(
	[Description] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

/****** Object:  Index [Procedure##EAPageSID]    Script Date: 08/01/2021 2:50:03 AM ******/
CREATE NONCLUSTERED INDEX [Procedure##EAPageSID] ON [dbo].[Procedure]
(
	[EAPageSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Procedure##Keywords]    Script Date: 08/01/2021 2:50:03 AM ******/
CREATE NONCLUSTERED INDEX [Procedure##Keywords] ON [dbo].[Procedure]
(
	[Keywords] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Procedure##PostMethod]    Script Date: 08/01/2021 2:50:03 AM ******/
CREATE NONCLUSTERED INDEX [Procedure##PostMethod] ON [dbo].[Procedure]
(
	[PostMethod] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Procedure##ProcedurePK]    Script Date: 08/01/2021 2:50:03 AM ******/
CREATE NONCLUSTERED INDEX [Procedure##ProcedurePK] ON [dbo].[Procedure]
(
	[ProcedureCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Procedure##RecordStatus]    Script Date: 08/01/2021 2:50:03 AM ******/
CREATE NONCLUSTERED INDEX [Procedure##RecordStatus] ON [dbo].[Procedure]
(
	[RecordStatus] ASC,
	[ProcedureCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Procedure##StatusClassCode]    Script Date: 08/01/2021 2:50:03 AM ******/
CREATE NONCLUSTERED INDEX [Procedure##StatusClassCode] ON [dbo].[Procedure]
(
	[RecordStatus] ASC,
	[Class] ASC,
	[ProcedureCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Procedure##StatusDescriptionCode]    Script Date: 08/01/2021 2:50:03 AM ******/
CREATE NONCLUSTERED INDEX [Procedure##StatusDescriptionCode] ON [dbo].[Procedure]
(
	[RecordStatus] ASC,
	[Description] ASC,
	[ProcedureCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Procedure##TOSCode]    Script Date: 08/01/2021 2:50:03 AM ******/
CREATE NONCLUSTERED INDEX [Procedure##TOSCode] ON [dbo].[Procedure]
(
	[TOSCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Procedure##UBCode]    Script Date: 08/01/2021 2:50:03 AM ******/
CREATE NONCLUSTERED INDEX [Procedure##UBCode] ON [dbo].[Procedure]
(
	[UBCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO


