USE [medman]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [PK__Provider__CE8778346ADA80FC]    Script Date: 08/01/2021 2:51:08 AM ******/
ALTER TABLE [dbo].[Provider] ADD PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

/****** Object:  Index [Provider##EMRProvider]    Script Date: 08/01/2021 2:51:08 AM ******/
CREATE NONCLUSTERED INDEX [Provider##EMRProvider] ON [dbo].[Provider]
(
	[EMRProvider] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

/****** Object:  Index [Provider##EncounterNoteProvider]    Script Date: 08/01/2021 2:51:08 AM ******/
CREATE NONCLUSTERED INDEX [Provider##EncounterNoteProvider] ON [dbo].[Provider]
(
	[EncounterNoteProvider] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

/****** Object:  Index [Provider##MMUser]    Script Date: 08/01/2021 2:51:08 AM ******/
CREATE NONCLUSTERED INDEX [Provider##MMUser] ON [dbo].[Provider]
(
	[MMUserSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Provider##Name]    Script Date: 08/01/2021 2:51:08 AM ******/
CREATE NONCLUSTERED INDEX [Provider##Name] ON [dbo].[Provider]
(
	[LastName] ASC,
	[FirstName] ASC,
	[MiddleName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

/****** Object:  Index [Provider##Omnidoc]    Script Date: 08/01/2021 2:51:08 AM ******/
CREATE NONCLUSTERED INDEX [Provider##Omnidoc] ON [dbo].[Provider]
(
	[OmniDocProvider] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

/****** Object:  Index [Provider##ProviderPK]    Script Date: 08/01/2021 2:51:08 AM ******/
CREATE NONCLUSTERED INDEX [Provider##ProviderPK] ON [dbo].[Provider]
(
	[ProviderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Provider##ProviderType]    Script Date: 08/01/2021 2:51:08 AM ******/
CREATE NONCLUSTERED INDEX [Provider##ProviderType] ON [dbo].[Provider]
(
	[ProviderType] ASC,
	[SortName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

/****** Object:  Index [Provider##RADProvider]    Script Date: 08/01/2021 2:51:08 AM ******/
CREATE NONCLUSTERED INDEX [Provider##RADProvider] ON [dbo].[Provider]
(
	[RADProvider] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Provider##SortName]    Script Date: 08/01/2021 2:51:08 AM ******/
CREATE NONCLUSTERED INDEX [Provider##SortName] ON [dbo].[Provider]
(
	[SortName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Provider##SSN]    Script Date: 08/01/2021 2:51:08 AM ******/
CREATE NONCLUSTERED INDEX [Provider##SSN] ON [dbo].[Provider]
(
	[SSN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

/****** Object:  Index [Provider##UltiaProvider]    Script Date: 08/01/2021 2:51:08 AM ******/
CREATE NONCLUSTERED INDEX [Provider##UltiaProvider] ON [dbo].[Provider]
(
	[UltiaProvider] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO


