export const columns = [
  {
    field: "activityTypeStr",
    title: "Activity Type",
    minWidth: 120,
    orderIndex: 1,
    filterable: true,
    filterType: "dropDown",
  },
  {
    field: "date",
    title: "From Date/Txn Date",
    minWidth: 120,
    orderIndex: 2,
    filterable: false,
  },
  {
    field: "claimNumber",
    title: "CN/ Description",
    minWidth: 150,
    orderIndex: 3,
    showToolTip: true,
    filterable: false,
  },
  {
    field: "chargetype",
    title: "Charge Type",
    minWidth: 90,
    orderIndex: 4,
    filterable: false,
  },
  {
    field: "procedurecode",
    title: "CPT/Txn",
    minWidth: 70,
    orderIndex: 5,
    filterable: false,
  },
  {
    field: "amount",
    title: "Amount",
    minWidth: 70,
    orderIndex: 6,
    type: "currency",
    isCustomCell: true,
    filterable: false,
  },
  {
    field: "approvedamount",
    title: "App. Amount",
    minWidth: 70,
    orderIndex: 7,
    type: "currency",
    isCustomCell: true,
    filterable: false,
  },
  {
    field: "balanceStr",
    title: "Balance",
    minWidth: 70,
    orderIndex: 8,
    type: "currency",
    isCustomCell: true,
    filterable: false,
  },
  {
    field: "currentStatus",
    title: "Current Status",
    minWidth: 100,
    orderIndex: 9,
    showToolTip: true,
    filterable: false,
  },
  {
    field: "patientstatment",
    title: "Pt. Statment",
    minWidth: 70,
    orderIndex: 10,
    filterable: false,
  },
  {
    field: "mod1",
    title: "Mod 1",
    minWidth: 50,
    orderIndex: 11,
    filterable: false,
  },
  {
    field: "mod2",
    title: "Mod 2",
    minWidth: 50,
    orderIndex: 12,
    filterable: false,
  },
  {
    field: "diag1",
    title: "Diag 1",
    minWidth: 50,
    orderIndex: 13,
    filterable: false,
  },
  {
    field: "diag2",
    title: "Diag 2",
    minWidth: 50,
    orderIndex: 14,
    filterable: false,
  },
  {
    field: "lowestRespCoverageOrder",
    title: "Responsapility",
    minWidth: 100,
    orderIndex: 15,
    filterable: false,
  },
  {
    field: "mod3",
    title: "Mod 3",
    minWidth: 50,
    orderIndex: 16,
    filterable: false,
    hide: true,
  },
  {
    field: "mod4",
    title: "Mod 4",
    minWidth: 50,
    orderIndex: 17,
    filterable: false,
    hide: true,
  },
  {
    field: "diag3",
    title: "Diag 3",
    minWidth: 50,
    orderIndex: 18,
    hide: true,
    filterable: false,
  },
  {
    field: "diag4",
    title: "Diag 4",
    minWidth: 50,
    orderIndex: 19,
    hide: true,
    filterable: false,
  },
];
