export const columns = [
  {
    field: "activityTypeStr",
    title: "Activity Type",
    minWidth: 100,
    orderIndex: 1,
  },
  {
    field: "date",
    title: "From Date/Txn Date",
    minWidth: 120,
    orderIndex: 2,
  },
  {
    field: "claimNumber",
      title: "CN/ Description",
    minWidth: 100,
    orderIndex: 3,
  },
  {
    field: "chargetype",
    title: "Charge Type",
    minWidth: 90,
    orderIndex: 4,
  },
  {
    field: "procedurecode",
    title: "CPT/Txn",
    minWidth: 70,
    orderIndex: 5,
  },
  {
    field: "amount",
    title: "Amount",
    minWidth: 70,
    orderIndex: 6,
    type: "currency",
    isCustomCell: true,
  },
  {
    field: "approvedamount",
    title: "Approved Amount",
    minWidth: 110,
    orderIndex: 7,
    type: "currency",
    isCustomCell: true,
  },
  {
    field: "currentStatus",
    title: "Current Status",
    minWidth: 100,
    orderIndex: 8,
    showToolTip: true,
  },
  {
    field: "patientstatment",
    title: "Patient Statment",
    minWidth: 100,
    orderIndex: 9,
  },
  {
    field: "mod1",
    title: "Mod 1",
    minWidth: 50,
    orderIndex: 11,
  },
  {
    field: "mod2",
    title: "Mod 2",
    minWidth: 50,
    orderIndex: 12,
  },
  {
    field: "diag1",
    title: "Diag 1",
    minWidth: 50,
    orderIndex: 15,
  },
  {
    field: "diag2",
    title: "Diag 2",
    minWidth: 50,
    orderIndex: 16,
  },
  {
    field: "activityCount",
    title: "Count",
    minWidth: 50,
    orderIndex: 19,
  },
  {
    field: "balanceStr",
    title: "Balance",
    minWidth: 100,
    orderIndex: 20,
  },
  {
    field: "amountStr",
    title: "Amount",
    minWidth: 100,
    orderIndex: 21,
    type: "currency",
    isCustomCell: true,
  },
  {
    field: "lowestRespCoverageOrder",
    title: "Resposapility",
    minWidth: 100,
    orderIndex: 22,
  },
];
