// patient
export const SET_PATIENTS = "SET_PATIENTS";
export const GET_PATIENTS_FAILED = "GET_PATIENTS_FAILED";
export const SET_PATIENT_TYPES = "SET_PATIENT_TYPES";
export const GET_PATIENT_TYPES_FAILED = "GET_PATIENT_TYPES_FAILED";
export const SET_PATIENT_FILTER = "SET_PATIENT_FILTER";
export const SET_PATIENT_LIST = "SET_PATIENT_LIST";
export const GET_PATIENT_lIST_FAILED = "GET_PATIENT_lIST_FAILED";
export const GET_PATIENT_FILTER_FAILED = "GET_PATIENT_TYPES_FAILED";
export const SET_PRACTICE = "SET_PRACTICE";
export const GET_PRACTICE_FAILED = "GET_PRACTICE_FAILED";
export const RESET_PATIENT_LIST = "RESET_PATIENT_LIST";
export const RESET_PATIENT_LIST_FAILED = "RESET_PATIENT_LIST_FAILED";
export const SET_INSURANCE_LIST = "SET_INSURANCE_LIST";
export const GET_INSURANCE_lIST_FAILED = "GET_INSURANCE_lIST_FAILED";
export const RESET_INSURANCE_LIST = "RESET_INSURANCE_LIST";
export const RESET_INSURANCE_LIST_FAILED = "RESET_INSURANCE_LIST_FAILED";
export const SET_PATIENT_LEDGER = "SET_PATIENT_LEDGER";
export const GET_PATIENT_LEDGER_FAILED = "GET_PATIENT_LEDGER_FAILED";
export const SET_COMPANIES = "SET_COMPANIES";
export const GET_COMPANIES_FAILED = "GET_COMPANIES_FAILED";
//UI
export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";
export const UI_EXPAND = "UI_EXPAND";
//FILTER
export const FILTER_DELETE = "FILTER_DELETE";
export const FILTER_DELETE_FAILED = "FILTER_DELETE_FAILED";
export const FILTER_INSERT = "FILTER_INSERT";
export const FILTER_INSERT_FAILED = "FILTER_INSERT_FAILED";
export const FILTER_UPDATE = "FILTER_UPDATE";
export const FILTER_UPDATE_FAILED = "FILTER_UPDATE_FAILED";
export const FILTERS_GET = "FILTERS_GET";
export const FILTERS_GET_FAILED = "FILTERS_GET_FAILED";
//PATIENT DETAILS
export const SET_PATIENTS_Details = "SET_PATIENTS_Details";

// Claim List
export const SET_CLAIMS = "SET_CLAIMS";
export const GET_CLAIMS_FAILED = "GET_CLAIMS_FAILED";
export const SET_CLAIM_DETAILS = "SET_CLAIM_DETAILS";
export const GET_CLAIM_DETAILS_FAILED = "GET_CLAIM_DETAILS_FAILED";
export const SET_CLAIM_FILTER = "SET_CLAIM_FILTER";
export const GET_CLAIM_FILTER_FAILED = "GET_CLAIM_FILTER_FAILED";
export const SET_GUARANTOR_LIST = "SET_GUARANTOR_LIST";
export const GET_GUARANTOR_lIST_FAILED = "GET_GUARANTOR_lIST_FAILED";
export const RESET_GUARANTOR_LIST = "RESET_GUARANTOR_LIST";
export const GETRESET_GUARANTOR_lIST_FAILED = "GETRESET_GUARANTOR_lIST_FAILED";
export const SUBMIT_CLAIMS = "SUBMIT_CLAIMS";
export const SUBMIT_CLAIMS_FAILED = "SUBMIT_CLAIMS_FAILED";
export const Parse_ERAMessages_FAILED = "Parse_ERAMessages_FAILED";
// Claim Detials
export const SET_CHARGES = "SET_CHARGES";
export const GET_CHARGES_FAILED = "GET_CHARGES_FAILED";
export const SET_CLAIM_SUBMISSION_HISTORY = "SET_CLAIM_SUBMISSION_HISTORY";
export const GET_CLAIM_SUBMISSION_HISTORY_FAILED =
    "GET_CLAIM_SUBMISSION_HISTORY_FAILED";
//LookUp List
export const FILTERS_PATIENTS = "FILTERS_PATIENTS";
export const FILTERS_INSURANCES = "FILTERS_INSURANCES";
export const FILTERS_GUARANTORS = "FILTERS_GUARANTORS";
export const FILTERS_PRACTICE = "FILTERS_PRACTICE";
export const FILTERS_PATIENTTYPE = "FILTERS_PATIENTTYPE";
export const FILTERS_PHYSICIAN = "FILTERS_PHYSICIAN";
export const FILTERS_CPT = "FILTERS_CPT";
export const FILTERS_ICD10 = "FILTERS_ICD10";
export const SET_PHYSICIAN_LIST = "SET_PHYSICIAN_LIST";
export const SET_PHYSICIAN_LIST_FAILED = "SET_PHYSICIAN_LIST_FAILED";
export const SET_COMPANIES_LIST = "SET_COMPANIES_LIST";
export const SET_COMPANIES_LIST_FAILED = "SET_COMPANIES_LIST_FAILED";
export const SET_PLAN_LIST = "SET_PLAN_LIST";
export const SET_PLAN_LIST_FAILED = "SET_PLAN_LIST_FAILED";


//Charge Details
export const ICD10_DIAGNOSIS = "ICD10_DIAGNOSIS";
export const ICD10_DIAGNOSIS_FAILED = "ICD10_DIAGNOSIS_FAILED";
export const CHARGE_DETAILS_GRID = "CHARGE_DETAILS_GRID";
export const CHARGE_DETAILS_GRID_FAILED = "CHARGE_DETAILS_GRID_FAILED";
export const CLAIM_NOTE = "CLAIM_NOTE";
export const CLAIM_NOTE_FAILED = "CLAIM_NOTE_FAILED";
export const CHARGE_ACTIVITY_GRID = "CHARGE_ACTIVITY_GRID";
export const CHARGE_ACTIVITY_GRID_FAILED = "CHARGE_ACTIVITY_GRID_FAILED";
export const CPT_LIST = "CPT_LIST";
export const CPT_LIST_FAILED = "CPT_LIST_FAILED";
export const GET_MODIFIER_LIST = "GET_MODIFIER_LIST";
export const GET_MODIFIER_LIST_FAILED = "GET_MODIFIER_LIST_FAILED";
// Account
export const USERID = "USERID";

// Grid Columns
export const GET_GRID_COLUMNS = "GET_GRID_COLUMNS";
export const GET_GRID_COLUMNS_FAILED = "GET_GRID_COLUMNS_FAILED";
export const SAVE_GRID_COLUMNS = "SAVE_GRID_COLUMNS";
export const SAVE_GRID_COLUMNS_FAILED = "SAVE_GRID_COLUMNS_FAILED";

// Insurance
export const GET_INSURANCE_RECORD_FAILED = "GET_INSURANCE_RECORD_FAILED";

//Payment
export const GET_PAYMENT_CLASS = "GET_PAYMENT_CLASS";
export const GET_PAYMENT_CLASS_FAILED = "GET_PAYMENT_CLASS_FAILED";
export const GET_PATIENT_PAYMENTS = "GET_PATIENT_PAYMENTS";
export const GET_PATIENT_PAYMENTS_FAILED = "GET_PATIENT_PAYMENTS_FAILED";
export const GET_INSURANCE_PAYMENTS = "GET_INSURANCE_PAYMENTS";
export const GET_INSURANCE_PAYMENTS_FAILED = "GET_INSURANCE_PAYMENTS_FAILED";
export const GET_PAYMENT_ASSIGNMENT = "GET_PAYMENT_ASSIGNMENT";
export const GET_PAYMENT_ASSIGNMENT_FAILS = "GET_PAYMENT_ASSIGNMENT_FAILS";
export const GET_APPLY_PATIENT_PAYMENTS = "GET_APPLY_PATIENT_PAYMENTS";
export const GET_APPLY_PATIENT_PAYMENTS_FAILS = "GET_APPLY_PATIENT_PAYMENTS_FAILS";

export const GET_APPLY_PLAN_PAYMENTS = "GET_APPLY_PATIENT_PAYMENTS";
export const GET_APPLY_PLAN_PAYMENTS_FAILS = "GET_APPLY_PATIENT_PAYMENTS_FAILS";
//ERA
export const GET_ERA_PAYMENTS = "GET_ERA_PAYMENTS";
export const GET_ERA_PAYMENTS_FAILS = "GET_ERA_PAYMENTS_FAILS";
export const POST_ERA_PAYMENTS_FAILS = "POST_ERA_PAYMENTS_FAILS";

//PHYSICIAN
export const GET_PHYSICIANS = "GET_PHYSICIANS";
export const GET_PHYSICIANS_FAILS = "GET_PHYSICIANS_FAILS";

export const GET_POSITION = "GET_POSITION";
export const GET_POSITION_FAILS = "GET_POSITION_FAILS";

//PLAN
export const GET_PLANS = "GET_PLANS";
export const GET_PLANS_FAILS = "GET_PLANS_FAILS";

export const GET_PLANS_GROUP = "GET_PLANS_GROUP";
export const GET_PLANS_GROUP_FAILS = "GET_PLANS_GROUP";

export const GET_FILES = "GET_FILES";
export const GET_FILES_FAILED = "GET_FILES_FAILED";

//Lookup

export const GET_LOOKUPS = "GET_LOOKUPS";
export const GET_LOOKUPS_FAILS = "GET_LOOKUPS_FAILS";

export const GET_LOOKUPS_TYPE = "GET_LOOKUPS_TYPE";
export const GET_LOOKUPS_TYPE_FAILS = "GET_LOOKUPS_TYPE_FAILS";

export const GET_LOOKUP_TYPES_Filter = "GET_LOOKUP_TYPES_Filter";
export const GET_LOOKUP_TYPES_Filter_FAILS = "GET_LOOKUP_TYPES_Filter_FAILS";







